# Generated by Django 3.1.1 on 2020-12-06 23:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cobook', '0002_cowork_zipcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Enter the booking end time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cowork',
            name='end_time',
            field=models.TimeField(default='20:00:00', help_text='Enter the booking end time'),
        ),
        migrations.AddField(
            model_name='cowork',
            name='start_time',
            field=models.TimeField(default='09:00:00', help_text='Enter the booking start time'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='end_time',
            field=models.TimeField(help_text='Enter the booking end time'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_time',
            field=models.TimeField(help_text='Enter the booking start time'),
        ),
    ]
